import sys
from pathlib import Path

import pytest

from briefcase.integrations.virtual_environment import (
    NoOpVirtualEnvironment,
    VirtualEnvironmentManager,
)


def test_manager(mock_tools):
    """A Venv environment can be generated by the manager."""
    VirtualEnvironmentManager.verify(mock_tools)

    assert mock_tools.virtual_environment[None] == NoOpVirtualEnvironment


@pytest.mark.parametrize("recreate", [True, False])
def test_create(noop_venv, recreate):
    """If the environment matches, prepare is a no-op."""

    # Environment always exists by default.
    assert noop_venv.exists()

    # Calling prepare causes the environment to be created
    # Return value says that it was created.
    assert noop_venv.prepare(recreate=recreate)

    # Environment still exists, and the marker path points at the executable.
    assert noop_venv.exists()
    assert noop_venv.marker_path.read_text(encoding="utf-8") == sys.executable


@pytest.mark.parametrize("recreate", [True, False])
def test_existing(noop_venv, recreate):
    """If the environment exists, it will only be created on a re-create."""
    # Create a marker file for the current executable.
    noop_venv.marker_path.parent.mkdir(parents=True)
    noop_venv.marker_path.write_text(sys.executable, encoding="utf-8")

    # Environment always exists.
    assert noop_venv.exists()

    # Calling prepare causes the environment to be created
    # If a recreate was requested, and the marker file existed, that is reflected in the result
    assert noop_venv.prepare(recreate=recreate) == recreate

    # Environment still exists, and the marker path points at the executable.
    assert noop_venv.exists()
    assert noop_venv.marker_path.read_text(encoding="utf-8") == sys.executable


@pytest.mark.parametrize("recreate", [True, False])
def test_environment_change(noop_venv, recreate):
    """If the environment marker exists, but doesn't match, marker is re-written."""
    # Create a marker file for a different executable.
    noop_venv.marker_path.parent.mkdir(parents=True)
    noop_venv.marker_path.write_text("Something else", encoding="utf-8")

    # Environment always exists.
    assert noop_venv.exists()

    # A change in environment is always a recreate
    assert noop_venv.prepare(recreate=recreate)

    # Environment still exists, and the marker path points at the executable.
    assert noop_venv.exists()
    assert noop_venv.marker_path.read_text(encoding="utf-8") == sys.executable


def test_prepare_creates_parent_directory(first_app, mock_tools, tmp_path):
    """Parent directories for the marker file are created on demand."""
    venv = NoOpVirtualEnvironment(
        "desert",
        app=first_app,
        tools=mock_tools,
        base_path=tmp_path / "deep" / "missing" / "venv",
    )

    assert venv.prepare()

    # Deep marker path file has been created
    assert venv.marker_path.is_file()


def test_strip_whitespace_from_marker(noop_venv):
    """A marker file with trailing whitespace still matches sys.executable."""
    noop_venv.marker_path.parent.mkdir(parents=True, exist_ok=True)
    noop_venv.marker_path.write_text(f"  {sys.executable}  \n", encoding="utf-8")

    result = noop_venv.prepare()

    assert result is False


def test_handles_oserror(noop_venv, monkeypatch):
    """If the marker can't be read, the environment is re-created."""
    noop_venv.marker_path.parent.mkdir(parents=True, exist_ok=True)
    noop_venv.marker_path.write_text("anything", encoding="utf-8")

    original_read = Path.read_text

    def boom(*args, **kwargs):
        raise OSError("Permission denied")

    monkeypatch.setattr(Path, "read_text", boom)
    result = noop_venv.prepare()

    assert result is True
    monkeypatch.setattr(Path, "read_text", original_read)
    assert noop_venv.marker_path.read_text(encoding="utf-8") == sys.executable


def test_handles_unicode_decode_error(noop_venv):
    """If the marker has bad encoding, it is re-written."""
    noop_venv.marker_path.parent.mkdir(parents=True, exist_ok=True)
    noop_venv.marker_path.write_bytes(b"\xff\xfe\xfd")

    result = noop_venv.prepare()

    assert result is True
    assert noop_venv.marker_path.read_text(encoding="utf-8") == sys.executable
