import subprocess
import sys
from unittest.mock import MagicMock

import pytest

from briefcase.exceptions import BriefcaseCommandError
from briefcase.integrations.virtual_environment import (
    UvVirtualEnvironment,
    VirtualEnvironmentManager,
)


def test_manager(mock_tools):
    """A Venv environment can be generated by the manager."""
    VirtualEnvironmentManager.verify(mock_tools)

    assert mock_tools.virtual_environment["uv"] == UvVirtualEnvironment


@pytest.mark.parametrize("recreate", [True, False])
def test_create(mock_tools, venv_path, recreate):
    """A Python venv can be created."""
    venv = UvVirtualEnvironment(mock_tools, venv_path, recreate=recreate)

    assert venv.created

    mock_tools.subprocess.run.assert_called_once_with(
        ["uv", "venv", "--python", sys.executable, "--seed", venv_path],
        check=True,
    )


def test_creates_parent_directory(mock_tools, tmp_path):
    """Environment parent directories on demand."""
    venv_path = tmp_path / "nested" / "missing" / "test_venv"
    venv = UvVirtualEnvironment(mock_tools, venv_path)

    assert venv.created
    assert venv_path.parent.is_dir()


def test_idempotent_when_venv_exists(mock_tools, venv_path):
    """If the environment already exists, creating the environment is a no-op."""
    venv_path.mkdir()
    (venv_path / "pyvenv.cfg").touch()

    venv = UvVirtualEnvironment(mock_tools, venv_path)

    assert not venv.created
    mock_tools.subprocess.run.assert_not_called()


def test_recreate(mock_tools, venv_path):
    """If an environment already exists, recreating can be triggered."""
    venv_path.mkdir()
    (venv_path / "pyvenv.cfg").touch()

    venv = UvVirtualEnvironment(mock_tools, venv_path, recreate=True)

    assert venv.created
    mock_tools.subprocess.run.assert_called_once_with(
        ["uv", "venv", "--python", sys.executable, "--seed", venv_path],
        check=True,
    )


def test_venv_failure(mock_tools, venv_path):
    """If the environment can't be created, BriefcaseCommandError is raised."""
    mock_tools.subprocess.run = MagicMock(
        side_effect=subprocess.CalledProcessError(returncode=1, cmd="venv")
    )

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Failed to create uv environment at ",
    ):
        UvVirtualEnvironment(mock_tools, venv_path)

    mock_tools.subprocess.run.assert_called_once_with(
        ["uv", "venv", "--python", sys.executable, "--seed", venv_path],
        check=True,
    )
