import subprocess
import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from briefcase.exceptions import BriefcaseCommandError
from briefcase.integrations.virtual_environment import (
    UvVirtualEnvironment,
    VirtualEnvironmentManager,
)

from ....utils import create_file


def test_manager(mock_tools):
    """A uv environment can be generated by the manager."""
    # Reset the verification status
    UvVirtualEnvironment.verified = False
    VirtualEnvironmentManager.verify(mock_tools)

    assert mock_tools.virtual_environment["uv"] == UvVirtualEnvironment

    # The existence of uv was verified.
    mock_tools.subprocess.check_output.assert_called_once_with(["uv", "--version"])

    # Verification only occurs on first use
    # Reset the mock, then get a second uv environment.
    mock_tools.subprocess.check_output.reset_mock()

    assert mock_tools.virtual_environment["uv"] == UvVirtualEnvironment
    mock_tools.subprocess.check_output.assert_not_called()


def test_uv_not_available(mock_tools):
    """If uv is not available, and error is raised during verification."""
    # Reset the verification status
    UvVirtualEnvironment.verified = False
    VirtualEnvironmentManager.verify(mock_tools)

    # Mock a failure of uv detection
    mock_tools.subprocess.check_output = MagicMock(
        side_effect=subprocess.CalledProcessError(returncode=1, cmd="uv --version")
    )

    with pytest.raises(BriefcaseCommandError, match=r"Could not find `uv`"):
        assert mock_tools.virtual_environment["uv"] == UvVirtualEnvironment

    # uv --version was invoked
    mock_tools.subprocess.check_output.assert_called_once_with(["uv", "--version"])


@pytest.mark.parametrize("recreate", [True, False])
def test_create(mock_tools, venv, base_path, recreate):
    """A uv venv can be created."""

    # Mock a side effect of calling run that creates the pyvenv.cfg marker file.
    def mock_run(cmd, *args, **kwargs):
        if cmd[:2] == ["uv", "venv"]:
            Path(cmd[-1]).mkdir(parents=True)
            (Path(cmd[-1]) / "pyvenv.cfg").write_text("", encoding="UTF-8")

    mock_tools.subprocess.run.side_effect = mock_run

    # venv does not initially exist
    assert not venv.exists()

    # venv was created, and now exists.
    assert venv.prepare(recreate=recreate)
    assert venv.exists()

    mock_tools.subprocess.run.assert_called_once_with(
        [
            "uv",
            "venv",
            "--python",
            sys.executable,
            "--seed",
            base_path / ".briefcase/first-app/uv-myenv",
        ],
        check=True,
    )


def test_creates_parent_directory(first_app, mock_tools, tmp_path):
    """Environment parent directories on demand."""
    venv_path = tmp_path / "nested" / "missing" / "test_venv"
    venv = UvVirtualEnvironment(
        name="myvenv",
        app=first_app,
        tools=mock_tools,
        base_path=venv_path,
    )

    assert venv.prepare()
    assert venv_path.parent.is_dir()


def test_idempotent_when_venv_exists(venv, mock_tools):
    """If the environment already exists, creating the environment is a no-op."""
    # Create a marker file for the venv
    create_file(venv.venv_path / "pyvenv.cfg", "exists")

    assert not venv.prepare()
    mock_tools.subprocess.run.assert_not_called()


def test_recreate(venv, mock_tools, base_path):
    """If an environment already exists, recreating can be triggered."""
    # Create a marker file for the venv
    create_file(venv.venv_path / "pyvenv.cfg", "exists")

    assert venv.prepare(recreate=True)
    mock_tools.subprocess.run.assert_called_once_with(
        [
            "uv",
            "venv",
            "--python",
            sys.executable,
            "--seed",
            base_path / ".briefcase/first-app/uv-myenv",
        ],
        check=True,
    )


def test_venv_failure(venv, mock_tools, base_path):
    """If the environment can't be created, BriefcaseCommandError is raised."""
    mock_tools.subprocess.run = MagicMock(
        side_effect=subprocess.CalledProcessError(returncode=1, cmd="venv")
    )

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Failed to create uv environment at ",
    ):
        venv.prepare()

    mock_tools.subprocess.run.assert_called_once_with(
        [
            "uv",
            "venv",
            "--python",
            sys.executable,
            "--seed",
            base_path / ".briefcase/first-app/uv-myenv",
        ],
        check=True,
    )
