import subprocess
import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from briefcase.exceptions import BriefcaseCommandError
from briefcase.integrations.virtual_environment import (
    CondaVirtualEnvironment,
    VirtualEnvironmentManager,
)

from ....utils import create_file

PYTHON_VERSION = f"{sys.version_info.major}.{sys.version_info.minor}"


def test_manager(mock_tools):
    """A Conda environment can be generated by the manager."""
    # Reset the verification status
    CondaVirtualEnvironment.verified = False
    VirtualEnvironmentManager.verify(mock_tools)

    # Mock a valid version of Conda
    mock_tools.subprocess.check_output = MagicMock(return_value="conda 26.5.3")

    # Retrieve the Conda env class.
    assert mock_tools.virtual_environment["conda"] == CondaVirtualEnvironment

    # The existence of conda was verified.
    mock_tools.subprocess.check_output.assert_called_once_with(["conda", "--version"])

    # Verification only occurs on first use
    # Reset the mock, then get a second conda environment.
    mock_tools.subprocess.check_output.reset_mock()

    assert mock_tools.virtual_environment["conda"] == CondaVirtualEnvironment
    mock_tools.subprocess.check_output.assert_not_called()


def test_conda_not_available(mock_tools):
    """If Conda is not available, and error is raised during verification."""
    # Reset the verification status
    CondaVirtualEnvironment.verified = False
    VirtualEnvironmentManager.verify(mock_tools)

    # Mock a failure of uv detection
    mock_tools.subprocess.check_output = MagicMock(
        side_effect=subprocess.CalledProcessError(returncode=127, cmd="conda --version")
    )

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Could not find a Conda installation",
    ):
        assert mock_tools.virtual_environment["conda"] == CondaVirtualEnvironment

    # uv --version was invoked
    mock_tools.subprocess.check_output.assert_called_once_with(["conda", "--version"])


def test_conda_too_old(mock_tools):
    """If Uv is not available, and error is raised during verification."""
    # Reset the verification status
    CondaVirtualEnvironment.verified = False
    VirtualEnvironmentManager.verify(mock_tools)

    # Mock an old version of Conda
    mock_tools.subprocess.check_output = MagicMock(return_value="conda 21.2.3")

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Briefcase requires Conda 26\.5 \(or newer\)\; you have 21\.2\.3",
    ):
        assert mock_tools.virtual_environment["conda"] == CondaVirtualEnvironment

    # conda --version was invoked
    mock_tools.subprocess.check_output.assert_called_once_with(["conda", "--version"])


@pytest.mark.parametrize("recreate", [True, False])
@pytest.mark.parametrize("verbose", [True, False])
def test_create(mock_tools, venv, base_path, recreate, verbose):
    """A conda environment can be created."""
    mock_tools.console.is_verbose = verbose

    # Mock a side effect of calling run that creates the pyvenv.cfg marker file.
    def mock_run(cmd, *args, **kwargs):
        if cmd[:2] == ["conda", "create"]:
            (Path(cmd[3]) / "conda-meta").mkdir(parents=True)

    mock_tools.subprocess.run.side_effect = mock_run

    # venv does not initially exist
    assert not venv.exists()

    # venv was created, and now exists.
    assert venv.prepare(recreate=recreate)
    assert venv.exists()

    mock_tools.subprocess.run.assert_called_once_with(
        [
            "conda",
            "create",
            "--prefix",
            base_path / ".briefcase/first-app/conda-myenv",
            "--yes",
        ]
        + ([] if verbose else ["--quiet"])
        + [
            f"python={PYTHON_VERSION}",
            "pip",
        ],
        check=True,
    )


def test_creates_parent_directory(first_app, mock_tools, tmp_path):
    """Environment parent directories are created on demand."""
    venv_path = tmp_path / "nested" / "missing" / "test_venv"
    venv = CondaVirtualEnvironment(
        name="myvenv",
        app=first_app,
        tools=mock_tools,
        base_path=venv_path,
    )

    assert venv.prepare()
    assert venv_path.parent.is_dir()


def test_idempotent_when_venv_exists(venv, mock_tools):
    """If the environment already exists, creating the environment is a no-op."""
    # Create a marker file for the venv
    create_file(venv.venv_path / "conda-meta/python.json", "exists")

    assert not venv.prepare()
    mock_tools.subprocess.run.assert_not_called()


def test_recreate(venv, mock_tools, base_path):
    """If an environment already exists, recreating can be triggered."""
    # Create a marker file for the venv
    create_file(venv.venv_path / "conda-meta/python.json", "exists")

    assert venv.prepare(recreate=True)
    mock_tools.subprocess.run.assert_called_once_with(
        [
            "conda",
            "create",
            "--prefix",
            base_path / ".briefcase/first-app/conda-myenv",
            "--yes",
            f"python={PYTHON_VERSION}",
            "pip",
        ],
        check=True,
    )


def test_venv_failure(venv, mock_tools, base_path):
    """If the environment can't be created, BriefcaseCommandError is raised."""
    mock_tools.subprocess.run = MagicMock(
        side_effect=subprocess.CalledProcessError(returncode=1, cmd="conda")
    )

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Failed to create Conda environment at ",
    ):
        venv.prepare()

    mock_tools.subprocess.run.assert_called_once_with(
        [
            "conda",
            "create",
            "--prefix",
            base_path / ".briefcase/first-app/conda-myenv",
            "--yes",
            f"python={PYTHON_VERSION}",
            "pip",
        ],
        check=True,
    )
