import subprocess
import sys
from unittest.mock import MagicMock, call

import pytest

from briefcase.exceptions import BriefcaseCommandError
from briefcase.integrations.virtual_environment import (
    PixiVirtualEnvironment,
    VirtualEnvironmentManager,
)

PYTHON_VERSION = f"{sys.version_info.major}.{sys.version_info.minor}"


def init_calls(venv_path):
    return [
        call(
            ["pixi", "init", venv_path],
            check=True,
        ),
        call(
            [
                "pixi",
                "add",
                "--manifest-path",
                venv_path,
                f"python=={PYTHON_VERSION}",
            ],
            check=True,
        ),
    ]


def test_manager(mock_tools):
    """A Venv environment can be generated by the manager."""
    VirtualEnvironmentManager.verify(mock_tools)

    assert mock_tools.virtual_environment["pixi"] == PixiVirtualEnvironment


@pytest.mark.parametrize("recreate", [True, False])
def test_create(mock_tools, venv_path, recreate):
    """A pixi workspace can be created."""
    venv = PixiVirtualEnvironment(mock_tools, venv_path, recreate=recreate)

    assert venv.created

    mock_tools.subprocess.run.assert_has_calls(init_calls(venv_path))
    assert mock_tools.subprocess.run.call_count == 2


def test_creates_parent_directory(mock_tools, tmp_path):
    """Workspace parent directories are created on demand."""
    venv_path = tmp_path / "nested" / "missing" / "test_venv"
    venv = PixiVirtualEnvironment(mock_tools, venv_path)

    assert venv.created
    assert venv_path.is_dir()


def test_idempotent_when_venv_exists(mock_tools, venv_path):
    """If the workspace already exists, creating the workspace is a no-op."""
    (venv_path / ".pixi" / "envs" / "default").mkdir(parents=True)
    (venv_path / "pixi.toml").touch()

    venv = PixiVirtualEnvironment(mock_tools, venv_path)

    assert not venv.created
    mock_tools.subprocess.run.assert_not_called()


def test_recreate(mock_tools, venv_path):
    """If a workspace already exists, recreating can be triggered."""
    (venv_path / ".pixi" / "envs" / "default").mkdir(parents=True)
    (venv_path / "pixi.toml").touch()

    venv = PixiVirtualEnvironment(mock_tools, venv_path, recreate=True)

    assert venv.created
    mock_tools.subprocess.run.assert_has_calls(init_calls(venv_path))
    assert mock_tools.subprocess.run.call_count == 2


def test_venv_failure(mock_tools, venv_path):
    """If the workspace can't be created, BriefcaseCommandError is raised."""
    mock_tools.subprocess.run = MagicMock(
        side_effect=subprocess.CalledProcessError(returncode=1, cmd="pixi")
    )

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Failed to create Pixi environment at ",
    ):
        PixiVirtualEnvironment(mock_tools, venv_path)

    mock_tools.subprocess.run.assert_called_once_with(
        ["pixi", "init", venv_path],
        check=True,
    )
