import subprocess
import sys
from pathlib import Path
from unittest.mock import ANY, MagicMock, call

import pytest

from briefcase.exceptions import BriefcaseCommandError
from briefcase.integrations.virtual_environment import (
    VenvVirtualEnvironment,
    VirtualEnvironmentManager,
)

from ....utils import create_file


def test_manager(mock_tools):
    """A Venv environment can be generated by the manager."""
    VirtualEnvironmentManager.verify(mock_tools)

    assert mock_tools.virtual_environment["venv"] == VenvVirtualEnvironment


@pytest.mark.parametrize("recreate", [True, False])
def test_create(venv, mock_tools, base_path, recreate):
    """A Python venv can be created."""

    # Mock a side effect of calling run that creates the pyvenv.cfg marker file.
    def mock_run(cmd, *args, **kwargs):
        if cmd[:3] == [sys.executable, "-m", "venv"]:
            Path(cmd[3]).mkdir(parents=True)
            (Path(cmd[3]) / "pyvenv.cfg").write_text("", encoding="UTF-8")

    mock_tools.subprocess.run.side_effect = mock_run

    # venv does not initially exist
    assert not venv.exists()

    # venv was created, and now exists.
    assert venv.prepare(recreate=recreate)
    assert venv.exists()

    assert mock_tools.subprocess.run.mock_calls == [
        call(
            [
                sys.executable,
                "-m",
                "venv",
                base_path / ".briefcase/first-app/venv-myenv",
            ],
            check=True,
        ),
        call(
            [
                venv.executable,
                "-u",
                "-X",
                "utf8",
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-user",
                "--upgrade",
                "-vv",
                "pip",
            ],
            check=True,
            encoding="UTF-8",
            env=ANY,
        ),
    ]


def test_creates_parent_directory(first_app, mock_tools, base_path):
    """Environment parent directories on demand."""
    venv_path = base_path / "nested" / "missing" / "test_venv"
    venv = VenvVirtualEnvironment(
        name="myvenv",
        app=first_app,
        tools=mock_tools,
        base_path=venv_path,
    )

    assert venv.prepare()
    assert venv_path.parent.is_dir()


def test_idempotent_when_venv_exists(venv, mock_tools, base_path):
    """If the environment already exists, creating the environment is a no-op."""
    # Create a marker file for the venv
    create_file(venv.venv_path / "pyvenv.cfg", "exists")

    assert not venv.prepare()
    mock_tools.subprocess.run.assert_not_called()


def test_recreate(venv, mock_tools, base_path):
    """If an environment already exists, recreating can be triggered."""
    # Create a marker file for the venv
    create_file(venv.venv_path / "pyvenv.cfg", "exists")

    assert venv.prepare(recreate=True)
    assert mock_tools.subprocess.run.mock_calls == [
        call(
            [
                sys.executable,
                "-m",
                "venv",
                base_path / ".briefcase/first-app/venv-myenv",
            ],
            check=True,
        ),
        call(
            [
                venv.executable,
                "-u",
                "-X",
                "utf8",
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-user",
                "--upgrade",
                "-vv",
                "pip",
            ],
            check=True,
            encoding="UTF-8",
            env=ANY,
        ),
    ]


def test_venv_failure(venv, mock_tools, base_path):
    """If the environment can't be created, BriefcaseCommandError is raised."""
    mock_tools.subprocess.run = MagicMock(
        side_effect=subprocess.CalledProcessError(returncode=1, cmd="venv")
    )

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Failed to create virtual environment at ",
    ):
        venv.prepare()

    mock_tools.subprocess.run.assert_called_once_with(
        [sys.executable, "-m", "venv", base_path / ".briefcase/first-app/venv-myenv"],
        check=True,
    )


def test_pip_upgrade_failure(venv, mock_tools, base_path):
    """If pip can't be upgraded, a BriefcaseCommandError is raised."""
    # Second subprocess call fails
    mock_tools.subprocess.run = MagicMock(
        side_effect=[
            0,
            subprocess.CalledProcessError(returncode=1, cmd="venv"),
        ]
    )

    with pytest.raises(
        BriefcaseCommandError,
        match=r"Failed to update core tooling for ",
    ):
        venv.prepare()

    assert mock_tools.subprocess.run.mock_calls == [
        call(
            [
                sys.executable,
                "-m",
                "venv",
                base_path / ".briefcase/first-app/venv-myenv",
            ],
            check=True,
        ),
        call(
            [
                ANY,
                "-u",
                "-X",
                "utf8",
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-user",
                "--upgrade",
                "-vv",
                "pip",
            ],
            check=True,
            encoding="UTF-8",
            env=ANY,
        ),
    ]
