name: New issue

on:
  issues:
    types:
      - opened
      - reopened
      - transferred

jobs:
  add-to-project:
    name: Add issue to BeeWare project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/orgs/beeware/projects/1
          github-token: ${{ secrets.BRUTUS_PAT_TOKEN }}
