name: Create Release

permissions: {}

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    permissions:
      id-token: write
      contents: read
      attestations: write
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      attest-package: "true"

  docs:
    permissions:
      contents: read
    name: Verify Docs Build
    uses: beeware/.github/.github/workflows/docs-build-verify.yml@741cc5a311012ee0ee195938889a337449d01eeb  # main
    secrets:
      RTD_API_TOKEN: ${{ secrets.RTD_API_TOKEN }}
    with:
      project-name: "briefcase"
      project-version: ${{ github.ref_name }}

  release:
    name: Create Release
    needs: [ ci, docs ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # This permission is required for trusted publishing.
      id-token: write
    steps:
      - name: Set build variables
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" | tee -a $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: "3.x"

      - name: Get packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          pattern: ${{ format('{0}*', needs.ci.outputs.artifact-basename) }}
          merge-multiple: true
          path: dist

      - name: Purge non-release packages
        run: rm -rf dist/x_*

      - name: Install packages
        run: pip install dist/*.whl

      - name: Check version number
        # Check that the setuptools_scm-generated version number is still the same when
        # installed from a wheel with setuptools_scm not present.
        run: |
          set -x
          test $(briefcase --version) = $VERSION

      - name: Create release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd  # v1.21.0
        with:
          name: ${{ env.VERSION }}
          draft: true
          artifacts: dist/${{ github.event.repository.name }}*
          artifactErrorsFailBuild: true

      - name: Publish release to Test PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247  # v1.14.0
        with:
          repository-url: https://test.pypi.org/legacy/
